# Generated by Django 4.2 on 2023-11-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_skill_delete_characteristic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='profile/files/education'),
        ),
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
