# Generated by Django 4.2 on 2023-11-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
