# Generated by Django 4.2 on 2023-11-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_education_start_date_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='certificate',
            new_name='imagenEduc',
        ),
    ]
