# Generated by Django 4.2 on 2023-06-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='technologies',
            options={'verbose_name': 'Technologie', 'verbose_name_plural': 'Technologies'},
        ),
    ]
